import 'package:flutter/material.dart';
import '../../../models/student.dart';

class AddStudentDialog extends StatefulWidget {
  final Future<void> Function(Map<String, dynamic> studentData) onAdd;

  const AddStudentDialog({super.key, required this.onAdd});

  @override
  State<AddStudentDialog> createState() => _AddStudentDialogState();
}

class _AddStudentDialogState extends State<AddStudentDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _progNameCtrl = TextEditingController();
  final _semCtrl = TextEditingController(text: '1');
  final _gpaCtrl = TextEditingController(text: '0.00');
  final _phoneCtrl = TextEditingController();

  String _selectedProgrammeType = 'Bachelor / Degree';
  String _selectedFaculty = 'FTMK';
  bool _isSubmitting = false;

  static const Map<String, String> _facultyCodes = {
    'FTMK': '03',
    'FTKM': '04',
    'FTKEK': '05',
    'FTKIP': '06',
    'FTKE': '07',
    'FPTT': '08',
  };

  static const Map<String, String> _programmeCodes = {
    'Diploma': 'D',
    'Bachelor / Degree': 'B',
    'Prasiswazah (Postgrad)': 'P',
  };

  @override
  void dispose() {
    _nameCtrl.dispose();
    _progNameCtrl.dispose();
    _semCtrl.dispose();
    _gpaCtrl.dispose();
    _phoneCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: const BorderSide(color: Colors.white10),
      ),
      title: Row(
        children: const [
          Icon(Icons.person_add_rounded, color: Color(0xFF00BFA5)),
          SizedBox(width: 10),
          Text(
            'Add New Student',
            style: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
              fontSize: 16,
            ),
          ),
        ],
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── ID Preview Banner ─────────────────────────
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 10,
                  ),
                  margin: const EdgeInsets.only(bottom: 16),
                  decoration: BoxDecoration(
                    color: const Color(0xFF00BFA5).withOpacity(0.07),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: const Color(0xFF00BFA5).withOpacity(0.25),
                    ),
                  ),
                  child: Row(
                    children: [
                      const Icon(
                        Icons.auto_awesome_rounded,
                        color: Color(0xFF00BFA5),
                        size: 16,
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text(
                              'Student ID — Auto-generated by server',
                              style: TextStyle(
                                color: Color(0xFF00BFA5),
                                fontWeight: FontWeight.bold,
                                fontSize: 11,
                              ),
                            ),
                            const SizedBox(height: 2),
                            Text(
                              'Format: [P][FF][YY][SC][NNN]  •  e.g. B032610001',
                              style: TextStyle(
                                color: Colors.white.withOpacity(0.35),
                                fontSize: 10,
                                fontFamily: 'monospace',
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),

                // ── Programme Type Dropdown ───────────────────
                const Text(
                  'Programme Type *',
                  style: TextStyle(
                    color: Colors.white54,
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                _buildDropdown(
                  value: _selectedProgrammeType,
                  items: _programmeCodes.keys.toList(),
                  onChanged: (val) {
                    if (val != null) {
                      setState(() => _selectedProgrammeType = val);
                    }
                  },
                ),
                const SizedBox(height: 12),

                // ── Faculty Dropdown ──────────────────────────
                const Text(
                  'Faculty *',
                  style: TextStyle(
                    color: Colors.white54,
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                _buildDropdown(
                  value: _selectedFaculty,
                  items: _facultyCodes.keys.toList(),
                  onChanged: (val) {
                    if (val != null) {
                      setState(() => _selectedFaculty = val);
                    }
                  },
                ),
                const SizedBox(height: 16),

                // ── Student Details ───────────────────────────
                const Text(
                  'Student Details',
                  style: TextStyle(
                    color: Colors.white54,
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),

                _buildDialogField(_nameCtrl, 'Full Name', Icons.person_outline_rounded, required: true),
                _buildDialogField(_progNameCtrl, 'Programme Name (e.g. Bachelor of CS)', Icons.school_outlined),
                _buildDialogField(_semCtrl, 'Current Semester  ← used in ID', Icons.calendar_today_outlined, isNumber: true),
                _buildDialogField(_gpaCtrl, 'GPA (0.00 – 4.00)', Icons.grade_outlined, isDecimal: true),
                _buildDialogField(_phoneCtrl, 'Phone Number', Icons.phone_outlined),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isSubmitting ? null : () => Navigator.of(context).pop(),
          child: const Text(
            'Cancel',
            style: TextStyle(color: Colors.white54),
          ),
        ),
        ElevatedButton.icon(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF00BFA5),
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
          icon: const Icon(Icons.save_rounded, size: 16),
          label: const Text(
            'Add Student',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          onPressed: _isSubmitting
              ? null
              : () async {
                  if (!_formKey.currentState!.validate()) return;
                  setState(() => _isSubmitting = true);

                  final body = {
                    'name': _nameCtrl.text.trim(),
                    'email': 'auto',
                    'programmeCode': _programmeCodes[_selectedProgrammeType]!,
                    'faculty': _selectedFaculty,
                    'semester': _semCtrl.text.trim().isEmpty ? '1' : _semCtrl.text.trim(),
                    'programme': _progNameCtrl.text.trim(),
                    'gpa': double.tryParse(_gpaCtrl.text.trim()) ?? 0.0,
                    'phoneNumber': _phoneCtrl.text.trim(),
                  };

                  try {
                    await widget.onAdd(body);
                    if (mounted) Navigator.of(context).pop();
                  } catch (e) {
                    setState(() => _isSubmitting = false);
                    if (mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text(e.toString().replaceAll('Exception: ', '')),
                          backgroundColor: Colors.redAccent,
                        ),
                      );
                    }
                  }
                },
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.04),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.white10),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          isExpanded: true,
          dropdownColor: const Color(0xFF2C2C2C),
          style: const TextStyle(color: Colors.white, fontSize: 13),
          icon: const Icon(Icons.arrow_drop_down, color: Colors.white38),
          items: items
              .map(
                (item) => DropdownMenuItem(
                  value: item,
                  child: Text(
                    item,
                    style: const TextStyle(color: Colors.white, fontSize: 13),
                  ),
                ),
              )
              .toList(),
          onChanged: onChanged,
        ),
      ),
    );
  }

  Widget _buildDialogField(
    TextEditingController ctrl,
    String label,
    IconData icon, {
    bool required = false,
    bool isNumber = false,
    bool isDecimal = false,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: TextFormField(
        controller: ctrl,
        style: const TextStyle(color: Colors.white),
        keyboardType: isDecimal
            ? const TextInputType.numberWithOptions(decimal: true)
            : isNumber
                ? TextInputType.number
                : TextInputType.text,
        decoration: InputDecoration(
          labelText: required ? '$label *' : label,
          labelStyle: TextStyle(
            color: required ? Colors.white70 : Colors.white54,
            fontSize: 13,
          ),
          prefixIcon: Icon(icon, color: Colors.white38, size: 18),
          filled: true,
          fillColor: Colors.white.withOpacity(0.04),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 12,
            vertical: 10,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.white10),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.white10),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF00BFA5), width: 1.2),
          ),
        ),
        validator: (v) => required && (v == null || v.trim().isEmpty) ? 'Field is required' : null,
      ),
    );
  }
}

class EditStudentDialog extends StatefulWidget {
  final Student student;
  final Future<void> Function(Map<String, dynamic> studentData) onSave;

  const EditStudentDialog({super.key, required this.student, required this.onSave});

  @override
  State<EditStudentDialog> createState() => _EditStudentDialogState();
}

class _EditStudentDialogState extends State<EditStudentDialog> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameCtrl;
  late final TextEditingController _emailCtrl;
  late final TextEditingController _progCtrl;
  late final TextEditingController _semCtrl;
  late final TextEditingController _gpaCtrl;
  late final TextEditingController _phoneCtrl;
  late String _selectedFaculty;
  bool _isSubmitting = false;

  static const Map<String, String> _facultyCodes = {
    'FTMK': '03',
    'FTKM': '04',
    'FTKEK': '05',
    'FTKIP': '06',
    'FTKE': '07',
    'FPTT': '08',
  };

  @override
  void initState() {
    super.initState();
    _nameCtrl = TextEditingController(text: widget.student.name);
    _emailCtrl = TextEditingController(text: widget.student.email);
    _progCtrl = TextEditingController(text: widget.student.programme ?? '');
    _semCtrl = TextEditingController(text: widget.student.semester ?? '1');
    _gpaCtrl = TextEditingController(text: widget.student.gpa.toString());
    _phoneCtrl = TextEditingController(text: widget.student.phoneNumber ?? '');
    _selectedFaculty = widget.student.faculty ?? 'FTMK';
    if (!_facultyCodes.containsKey(_selectedFaculty)) {
      _selectedFaculty = 'FTMK';
    }
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _emailCtrl.dispose();
    _progCtrl.dispose();
    _semCtrl.dispose();
    _gpaCtrl.dispose();
    _phoneCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: const BorderSide(color: Colors.white10),
      ),
      title: Row(
        children: [
          const Icon(Icons.edit_rounded, color: Color(0xFF3F51B5)),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              'Edit: ${widget.student.studentId}',
              style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
                fontSize: 15,
              ),
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ],
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Student ID — read-only
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  margin: const EdgeInsets.only(bottom: 10),
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.04),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.white10),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.badge_outlined, color: Colors.white30, size: 16),
                      const SizedBox(width: 10),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Student ID (Read-Only)',
                            style: TextStyle(color: Colors.white30, fontSize: 10),
                          ),
                          Text(
                            widget.student.studentId,
                            style: const TextStyle(
                              color: Colors.white54,
                              fontFamily: 'monospace',
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                const Text(
                  'Faculty *',
                  style: TextStyle(
                    color: Colors.white54,
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                _buildDropdown(
                  value: _selectedFaculty,
                  items: _facultyCodes.keys.toList(),
                  onChanged: (val) {
                    if (val != null) {
                      setState(() => _selectedFaculty = val);
                    }
                  },
                ),
                const SizedBox(height: 12),
                _buildDialogField(_nameCtrl, 'Full Name', Icons.person_outline_rounded, required: true),
                _buildDialogField(_emailCtrl, 'Email Address', Icons.email_outlined, required: true, readOnly: true),
                _buildDialogField(_progCtrl, 'Programme Name', Icons.school_outlined),
                _buildDialogField(_semCtrl, 'Semester', Icons.calendar_today_outlined, isNumber: true),
                _buildDialogField(_gpaCtrl, 'GPA (0.00 - 4.00)', Icons.grade_outlined, isDecimal: true),
                _buildDialogField(_phoneCtrl, 'Phone Number', Icons.phone_outlined),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isSubmitting ? null : () => Navigator.of(context).pop(),
          child: const Text(
            'Cancel',
            style: TextStyle(color: Colors.white54),
          ),
        ),
        ElevatedButton.icon(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF3F51B5),
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
          icon: const Icon(Icons.save_rounded, size: 16),
          label: const Text(
            'Save Changes',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          onPressed: _isSubmitting
              ? null
              : () async {
                  if (!_formKey.currentState!.validate()) return;
                  setState(() => _isSubmitting = true);

                  final body = {
                    'name': _nameCtrl.text.trim(),
                    'email': _emailCtrl.text.trim(),
                    'programme': _progCtrl.text.trim(),
                    'faculty': _selectedFaculty,
                    'semester': _semCtrl.text.trim().isEmpty ? '1' : _semCtrl.text.trim(),
                    'gpa': double.tryParse(_gpaCtrl.text.trim()) ?? 0.0,
                    'phoneNumber': _phoneCtrl.text.trim(),
                  };

                  try {
                    await widget.onSave(body);
                    if (mounted) Navigator.of(context).pop();
                  } catch (e) {
                    setState(() => _isSubmitting = false);
                    if (mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text(e.toString().replaceAll('Exception: ', '')),
                          backgroundColor: Colors.redAccent,
                        ),
                      );
                    }
                  }
                },
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.04),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.white10),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          isExpanded: true,
          dropdownColor: const Color(0xFF2C2C2C),
          style: const TextStyle(color: Colors.white, fontSize: 13),
          icon: const Icon(Icons.arrow_drop_down, color: Colors.white38),
          items: items
              .map(
                (item) => DropdownMenuItem(
                  value: item,
                  child: Text(
                    item,
                    style: const TextStyle(color: Colors.white, fontSize: 13),
                  ),
                ),
              )
              .toList(),
          onChanged: onChanged,
        ),
      ),
    );
  }

  Widget _buildDialogField(
    TextEditingController ctrl,
    String label,
    IconData icon, {
    bool required = false,
    bool isNumber = false,
    bool isDecimal = false,
    bool readOnly = false,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: TextFormField(
        controller: ctrl,
        readOnly: readOnly,
        style: TextStyle(color: readOnly ? Colors.white54 : Colors.white),
        keyboardType: isDecimal
            ? const TextInputType.numberWithOptions(decimal: true)
            : isNumber
                ? TextInputType.number
                : TextInputType.text,
        decoration: InputDecoration(
          labelText: required ? '$label *' : label,
          labelStyle: TextStyle(
            color: readOnly
                ? Colors.white30
                : required
                    ? Colors.white70
                    : Colors.white54,
            fontSize: 13,
          ),
          prefixIcon: Icon(icon, color: readOnly ? Colors.white24 : Colors.white38, size: 18),
          filled: true,
          fillColor: readOnly ? Colors.white.withOpacity(0.02) : Colors.white.withOpacity(0.04),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 12,
            vertical: 10,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.white10),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.white10),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: BorderSide(
              color: readOnly ? Colors.white10 : const Color(0xFF00BFA5),
              width: readOnly ? 1.0 : 1.2,
            ),
          ),
        ),
        validator: (v) => required && !readOnly && (v == null || v.trim().isEmpty) ? 'Field is required' : null,
      ),
    );
  }
}
